language: elixir

elixir:
  - 1.1.1
  - 1.2.0

otp_release:
  - 17.4
  - 18.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nkf mecab mecab-ipadic mecab-ipadic-utf8 -y

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
