language: elixir

elixir:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6

otp_release:
  - 18.3
  - 19.3
  - 20.3

matrix:
  exclude:
    - elixir: 1.1
      otp_release: 19.3
    - elixir: 1.1
      otp_release: 20.3
    - elixir: 1.2
      otp_release: 20.3
    - elixir: 1.3
      otp_release: 20.3
    - elixir: 1.4
      otp_release: 20.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nkf mecab mecab-ipadic mecab-ipadic-utf8 -y

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
